### PR TITLE
Uniform json and text formats + supplemental background changes/effects

### PR DESCRIPTION
**Pull request by Archthebald**
I made the steps follow roughly the same pattern, and reformatted the Json/calming_1.cpp
Also I added some template background changes and cwave effects
:fireworks:

### CODE REVIEW

**Comment by underscoredam** [comment]
Hey, I don't understand the use of `cwave_barage`. Why are there repeated lifevents being created? Perhaps you wanted to make them appear bolder? In that case, just reduce "damping". The cwave follows this equation:

intensity = (initial_intensity) * e^(-dampening_const * time)

which is how waves flow in real life. If you reduce the dampening_const, you can make it appear bolder.

**Comment by underscoredam** [comment]
Also, `bg_trans_*`s are not being used. Perhaps you want to refractor or remove them?

**Comment by Archthebald** [comment]
`cwave_damper`: I didn't necessarily want them all to be in the same location its just to show several different cwaves at a given event.

`bg_trans_*`: Basically prototyping for use in future transitions.

I'll exclude the both of those for now since they are not required by anything currently.

**Comment by underscoredam** [comment]
Awesome!

**Pull request merged**
